### ISSUE TITLE
NodeShared.cc:96:48: error: no matching function for call to ‘zmq::message_t::message_t(const char*, std: :__cxx11::basic_string<char>::size_type)’

### ISSUE THREAD

**Issue by vmatare** [ignitionrobotics/ign-transport#138] opened 2020-05-15 00:23 UTC
When compiling the 8.0.0 release, I get:
```
/var/tmp/portage/net-libs/ignition-transport-8.0.0/work/ignition-transport8_8.0.0/src/NodeShared.cc: In function ‘int sendHelper(zmq::socket_t&, const string&, int)’:                         
/var/tmp/portage/net-libs/ignition-transport-8.0.0/work/ignition-transport8_8.0.0/src/NodeShared.cc:96:48: error: no matching function for call to ‘zmq::message_t::message_t(const char*, std:
:__cxx11::basic_string<char>::size_type)’                                                                                                                                                      
   96 |   zmq::message_t msg(_data.data(), _data.size());                                                                                                                                      
      |                                                ^                                                                                                                                       
In file included from /var/tmp/portage/net-libs/ignition-transport-8.0.0/work/ignition-transport8_8.0.0/src/NodeShared.cc:21:                                                                  
/usr/include/zmq.hpp:258:9: note: candidate: ‘zmq::message_t::message_t(const zmq::message_t&)’                                                                                                
  258 |         message_t (const message_t&);                                                                                                                                                  
      |         ^~~~~~~~~                                                                                                                                                                      
/usr/include/zmq.hpp:258:9: note:   candidate expects 1 argument, 2 provided                                                                                                                   
/usr/include/zmq.hpp:165:16: note: candidate: ‘zmq::message_t::message_t(zmq::message_t&&)’                                                                                                    
  165 |         inline message_t (message_t &&rhs) : msg (rhs.msg)                                                                                                                             
      |                ^~~~~~~~~                                                                                                                                                               
/usr/include/zmq.hpp:165:16: note:   candidate expects 1 argument, 2 provided                                                                                                                  
/usr/include/zmq.hpp:156:16: note: candidate: ‘zmq::message_t::message_t(void*, size_t, void (*)(void*, void*), void*)’                                                                        
  156 |         inline message_t (void *data_, size_t size_, free_fn *ffn_,                                                                                                                    
      |                ^~~~~~~~~                                                                                                                                                               
/usr/include/zmq.hpp:156:16: note:   candidate expects 4 arguments, 2 provided                                                                                                                 
/usr/include/zmq.hpp:149:25: note: candidate: ‘zmq::message_t::message_t(size_t)’              
  149 |         inline explicit message_t (size_t size_)                                       
      |                         ^~~~~~~~~                                                                                                                                                      
/usr/include/zmq.hpp:149:25: note:   candidate expects 1 argument, 2 provided                                                                                                                  
/usr/include/zmq.hpp:142:16: note: candidate: ‘zmq::message_t::message_t()’                                                                                                                    
  142 |         inline message_t ()                                                                                                                                                            
      |                ^~~~~~~~~                                                                                                                                                               
/usr/include/zmq.hpp:142:16: note:   candidate expects 0 arguments, 2 provided
```

Same thing happens with the current master. Looks to me like the `free_fn *` required by the 4-argument constructor is simply missing...

**Comment by vmatare** [comment] 2020-05-15 00:43
Taking a closer look at the cmake, I see that various things are not found:
```
Protobuf_DIR:PATH=Protobuf_DIR-NOTFOUND
ZeroMQ_DIR:PATH=ZeroMQ_DIR-NOTFOUND
```
Other things are `NOTFOUND`, too, but these things look like I should be getting cmake errors about it, which I'm not.

**Comment by caguero** [comment] 2020-05-21 15:51
I cannot reproduce this issue. Could you check if in `/usr/include/zmq.hpp` you have a `message_t` constructor with this signature?

**Comment by caguero** [comment] 2020-06-06 13:57
I'm closing this issue, please reopen if the issue persists.

**Closed by caguero** 2020-06-06 13:57 UTC
