### ISSUE TITLE
MacOS dylib error when installing with binary (ignition-transport8: stable 8.2.0 (bottled))

### ISSUE THREAD

**Issue by ryanhugh** [ignitionrobotics/ign-transport#248] opened 2021-06-13 17:47 UTC
## Environment
* OS Version: Mac OS 11.4 
* Source or binary build? Binary: osrf/simulation/ignition-transport8: stable 8.2.0 (bottled)

I had an issue installing gazebo11 on MacOS. Running these commands (from here http://gazebosim.org/tutorials?tut=install_on_mac&cat=install)

``` 
brew tap osrf/simulation
brew install gazebo11
gazebo
``` 
resulted in the following issue: 

``` 
~/D/c/s/p/plugin (master)> gazebo
dyld: lazy symbol binding failed: Symbol not found: __ZN8ignition4msgs9DiscoveryC1EPN6google8protobuf5ArenaE
  Referenced from: /usr/local/opt/ignition-transport8/lib/libignition-transport8.8.dyld: lazy symbol binding faileddylib
  Expected in: /usr/local/: Symbol not found: __ZN8ignitioopt/ignition-msgs5/lib/libignitin4msgs9DiscoveryC1EPN6google8proon-msgs5.5.dylib

tobuf5ArenaE
  Referenced from: /usr/local/opt/ignition-transport8/lib/libignition-transport8.8.dyld: Symbol not found: __ZN8igndylib
  Expected in: /usr/local/ition4msgs9DiscoveryC1EPN6googleopt/ignition-msgs5/lib/libigniti8protobuf5ArenaE
  Referenced fron-msgs5.5.dylib

om: /usr/local/opt/ignition-transport8/lib/libignition-transport8.8.dylib
  Expected in: /usr/lodyld: Symbol not found: __ZN8igncal/opt/ignition-msgs5/lib/libigition4msgs9DiscoveryC1EPN6googlenition-msgs5.5.dylib

8protobuf5ArenaE
  Referenced from: /usr/local/opt/ignition-transport8/lib/libignition-transport8.8.dylib
  Expected in: /usr/local/opt/ignition-msgs5/lib/libignition-msgs5.5.dylib
``` 

I reinstalled ign-transport8 from source (first ran `brew uninstall --ignore-dependencies ignition-transport8`) and the error went away and everything worked again (following instructions [here](http://gazebosim.org/tutorials?tut=install_dependencies_from_source&cat=install)): 

Looks like there might be an issue with the latest binary in homebrew. The latest commit on ign-transport8 (as of today) is 5d88091eb5eb1c65a0faa37969b1cde9ce943c85.

**Comment by chapulina** [comment] 2021-06-14 23:23
This looks like a duplicate of https://github.com/osrf/homebrew-simulation/issues/1504. The solution is probably related to rebuilding homebrew bottles, and not in the source code. So I'm closing this issue in favor of that one.

**Closed by chapulina** 2021-06-14 23:23 UTC
Labels: bug, macOS
